### ISSUE TITLE
Missing property on Select component

### ISSUE THREAD

**Issue by ljmotta** [aerogear/uniforms-patternfly#55]
Hi, I'm currently working on the [Kogito Tooling](https://github.com/kiegroup/kogito-tooling) project, and we're considering to use this library to generate our forms. I've came across a bug on the `Select` component where it's missing the `isOpen` property.

Adding to that, the build and tests are not passing due to some broken libraries.

If it's not a problem, I can send a PR with these fixes together with a Patternfly update to the last release.

And just one last thing, I've observed on `tsconfig.json` file that the strict mode is off, causing the compiler to not make `null` checks and make it possible for implicit `any` types. And I must ask, this has any particular reason or can be changed to the strict mode?

**Comment by wtrocki** [comment]
+100 on community contribution. We stayed with current version for patternfly support. 

I think here we have PR with version bumps that can be updated.
https://github.com/aerogear/uniforms-patternfly/pull/46

**Comment by kingsleyzissou** [comment]
@ljmotta yes, please go ahead and put a PR in. The issue was that the Patternfly versions were changing so quickly and we pinned it to a certain version when we were developing this. 

The reason for the `tsconfig.json` having strict mode off was that this started out as a fork of the `uniforms` library and the config was the same as theirs, If I recall correctly.

I am also happy to help with reviews. I have been meaning to come back to this and the ionic version to get things in order and get things up to date, but would definitely appreciate the help.

**Comment by ljmotta** [comment]
Thanks for the quick reply.

@wtrocki  Great! I'll be using https://github.com/aerogear/uniforms-patternfly/pull/46 as reference to update the outdated libraries.

@kingsleyzissou Oh.. so it's better to keep the strict mode off if it comes from the original library. :grin:

**Comment by kingsleyzissou** [comment]
@ljmotta feel free to change it to strict mode on. It's more that I didn't give it much thought at the time. But it makes sense, as you pointed out to use strict mode

**Comment by ljmotta** [comment]
@kingsleyzissou OK! If it's not a problem, I'll make a separte PR for that because it can require more time to do it.

**Comment by AjayJagan** [comment]
Hello! I am from the Kogito Consoles team. I faced an issue in typescript while trying to update patternfly to the latest version. After having a discussion with @wtrocki , we came to a conclusion that this issue could be solved by updating the patternfly to latest .
Thanks for raising the issue :)

**Comment by wtrocki** [comment]
FYI new version was released today

**Comment by ederign** [comment]
@wtrocki thank you for quickly reviewing and releasing this!

**Comment by ljmotta** [comment]
@wtrocki Thank you for your quickly review!
