### ISSUE TITLE
Use Typescript strict mode

### ISSUE THREAD

**Issue by ljmotta** [aerogear/uniforms-patternfly#58]
As mentioned on #55 the TypeScript [strict mode](https://www.typescriptlang.org/tsconfig#strict)  is not being used. The strict mode enables several checks on compile time, which improves the code quality and mitigates possible run time errors. Also, I've observed some unused types, such as [BoolFieldProps](https://github.com/aerogear/uniforms-patternfly/blob/master/src/BoolField.tsx#L5).

About the project specifics, I've got curious about the components props type (like the `BoolFieldProps` that I had mentioned). Has it any particular reason to not use the `HMTLFieldProps` or `FieldProps` types provided by `uniforms`? Because as far I could see, it generates the correct component props type.

If it is not a problem, I can start working on enabling the strict mode and on the unused types.

**Comment by wtrocki** [comment]
Great idea. I have enabled it and there are some errors that would be trivial to fix.

CC @kingsleyzissou
