### ISSUE TITLE
Nested forms visibility issues

### ISSUE THREAD

**Issue by pefernan** [aerogear/uniforms-patternfly#6]
In our project we want to render automatic forms for json-schemas that may have more than one nested object on it, ([for example](https://gist.github.com/pefernan/7dfe047edda43ef2896e11ccd6b1ad32)).

In this case our schema has the following properties:

- flight: object
- hotel: object
  - address: object (nested to hotel)

When rendering an autoform, it correctly generates the form with two nested fields for flight and hotel and inside of hotel another one for address. But there are some visibilty issues that may be addressed:

- There is some spacing missing inside the nested fields. This appears to be related to a div that wraps the nested form that kind of breaks the grid.
- Since the form shows all fields at same level, It's hard to see what fields belong to what object. In the attached screenshot it's possible to see that on the **Hotel** nested form, we have the **Address** nested form, and just after it there are other fields that belong the **Hotel** (Booking Number, Name, Phone & Room).

![image](https://user-images.githubusercontent.com/2429832/87032936-a64da780-c1e5-11ea-8173-5330f019bccd.png)

**Comment by kingsleyzissou** [comment]
#9

**Comment by kingsleyzissou** [comment]
@pefernan this is sorted now and we've release `v0.1.0`
