### ISSUE TITLE
Disabled states for nested forms

### ISSUE THREAD

**Issue by pefernan** [aerogear/uniforms-patternfly#7]
In our project we want to render automatic forms for json-schemas that may have more than one nested object on it, ([for example](https://gist.github.com/pefernan/7dfe047edda43ef2896e11ccd6b1ad32)).

In this case our schema has the following properties:

- flight: object
- hotel: object
  - address: object (nested to hotel)

For us, it is possible to want to disable the full nested form to avoid the user modifying the data there. We tried  by using the `uniforms: {disabled: true}` attribute on the json-schema but this seems to not work properly.

**Comment by kingsleyzissou** [comment]
#8

**Comment by kingsleyzissou** [comment]
@pefernan this is sorted now and we've release `v0.1.0`
